namespace checkin4you.Shared.Models
{
    public partial class TblGuests2
    {
        public Guid Idguest { get; set; }
        public string? Phone { get; set; }
        public string? Fax { get; set; }
        public string? Mobile { get; set; }
        public string? CompanyPhone { get; set; }
        public string? Email { get; set; }
        public string? Homepage { get; set; }
        public byte[]? Tstamp { get; set; }
        public string? Comment { get; set; }
        public string? LetterSalutation { get; set; }
        public string? VehicleNo { get; set; }
        public string? Job { get; set; }
        public string? TableCode { get; set; }
        public Guid? Idsex { get; set; }
        public string? AdditionalComment { get; set; }
        public string? AdditionalCommentRtf { get; set; }
        public Guid? IdtravelDocument { get; set; }
        public string? TravelDocumentNo { get; set; }
        public DateTime? TravelDocumentDate { get; set; }
        public string? TravelDocumentCity { get; set; }
        public string? TravelDocumentBirthCity { get; set; }
        public Guid? IdpaymentType { get; set; }
        public Guid? IdpaymentCondition { get; set; }
        public string? CreditCardNo { get; set; }
        public string? CreditCardOwner { get; set; }
        public string? CreditCardValidTo { get; set; }
        public string? LetterName1 { get; set; }
        public string? LetterName2 { get; set; }
        public string? LetterName3 { get; set; }
        public decimal? RebateArra { get; set; }
        public string? InsurancePolNo { get; set; }
        public string? Misc { get; set; }
        public string? InsurancePol { get; set; }
        public Guid? IdfinancialAccount { get; set; }
        public string? VatidentNo { get; set; }
        public string? MotiveInfo { get; set; }
        public string? FamilyLetterSalutation { get; set; }
        public string? Phone2 { get; set; }
        public string? CompanyPhone2 { get; set; }
        public string? Email2 { get; set; }
        public string? Email3 { get; set; }
        public Guid? IdhealthInsurance { get; set; }
        public Guid? IdfamilyDoctor { get; set; }
        public string? MatchCode { get; set; }
        public decimal? RebateAmount { get; set; }
        public bool? Vip { get; set; }
        public string? Misc2 { get; set; }
        public Guid? IdinsurancePayer { get; set; }
        public Guid? IddefaultArrangement { get; set; }
        public Guid? IddefaultBookingMotive { get; set; }
        public Guid? IddefaultMarketCode { get; set; }
        public Guid? IddefaultSourceCode { get; set; }
        public Guid? IddefaultPersonType { get; set; }
        public Guid? Idagent { get; set; }
        public string? JobPosition { get; set; }
        public string? Iban { get; set; }
        public string? Bic { get; set; }
        public string? SubjectInfo1 { get; set; }
        public string? RatingInfo1 { get; set; }
        public string? SubjectInfo2 { get; set; }
        public string? SubjectInfo3 { get; set; }
        public string? Salutation { get; set; }
        public string? Idextern { get; set; }
        public DateTime? LastImportDate { get; set; }
        public bool? GuestExtraBool1 { get; set; }
        public bool? GuestExtraBool2 { get; set; }
        public int? GuestExtraInt1 { get; set; }
        public int? GuestExtraInt2 { get; set; }
        public string? GuestExtraString1 { get; set; }
        public bool? IsResBlocked { get; set; }
        public string? SubjectInfo4 { get; set; }
        public string? SubjectInfo5 { get; set; }
        public int? HabitationNo { get; set; }
        public int? HabitationDays { get; set; }
        public DateTime? GuestExtraDate1 { get; set; }
        public DateTime? GuestExtraDate2 { get; set; }
        public Guid? IdinvoiceNoRange { get; set; }
        public Guid? IdinsuranceInvoiceLocation { get; set; }
        public int? ContractPartnerNo { get; set; }
        public string? SpecialismField { get; set; }
        public bool? IsRoomOwner { get; set; }
        public short? DisabilityDegree { get; set; }
    }
}
